# Generated by Django 4.0.1 on 2022-01-10 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('businessentity', models.CharField(choices=[('集团', '集团'), ('管委会', '管委会')], max_length=6)),
                ('task_state', models.CharField(choices=[('前期', '前期'), ('设计', '设计'), ('招标', '招标'), ('合同流程', '合同流程'), ('实施', '实施'), ('完结', '完结'), ('暂停', '暂停')], max_length=10)),
                ('transactor', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lcdate', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True)),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_projects', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lcdate', models.DateTimeField(auto_now=True)),
                ('transactor', models.CharField(max_length=32)),
                ('remark', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='projects.project')),
            ],
        ),
    ]
