# Generated by Django 4.0.1 on 2023-08-19 10:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='项目名')),
                ('businessentity', models.CharField(choices=[('集团', '集团'), ('管委会', '管委会')], default='集团', max_length=6, verbose_name='主体')),
                ('task_state', models.CharField(choices=[('前期', '前期'), ('设计', '设计'), ('招标', '招标'), ('合同流程', '合同流程'), ('实施', '实施'), ('验收完成', '验收完成'), ('完成', '完成'), ('暂停', '暂停'), ('其他', '其他')], default='其他', max_length=20, verbose_name='状态')),
                ('transactor', models.CharField(max_length=32, verbose_name='经办人')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='金额')),
                ('content', models.TextField(blank=True, verbose_name='内容简介')),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('lcdate', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.structure', verbose_name='部门')),
                ('lcuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_projects', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_projects', to='projects.project', verbose_name='父项目')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='事项')),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('lcdate', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('task_type', models.CharField(choices=[('进度', '进度'), ('付款', '付款'), ('会议', '会议'), ('流程', '流程'), ('发文', '发文'), ('招采审核', '招采审核'), ('方案评审会', '方案评审会'), ('其他', '其他')], max_length=20, null=True, verbose_name='类型')),
                ('transactor', models.CharField(max_length=32, verbose_name='经办人')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('iskey', models.BooleanField(default=False, verbose_name='是否关键节点')),
                ('isfin', models.BooleanField(default=False, verbose_name='是否完成')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='进度占比')),
                ('deadline', models.DateTimeField(null=True, verbose_name='截止日期')),
                ('remark', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_schedules', to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.structure', verbose_name='部门')),
                ('lcuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_schedules', to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='projects.project', verbose_name='')),
            ],
        ),
    ]
