# Generated by Django 4.0.1 on 2022-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task_state',
            field=models.CharField(choices=[('前期', '前期'), ('设计', '设计'), ('招标', '招标'), ('合同流程', '合同流程'), ('实施', '实施'), ('验收', '验收'), ('完结', '完结'), ('暂停', '暂停')], max_length=10),
        ),
    ]
