# Generated by Django 4.0.1 on 2022-01-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_cuser_project_lcuser_schedule_cuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
