# Generated by Django 4.0.1 on 2023-08-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_structure_alter_oauser_department'),
        ('projects', '0003_schedule_task_type_alter_project_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.structure', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.structure', verbose_name='部门'),
        ),
    ]
