# Generated by Django 4.0.1 on 2023-08-05 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_department_alter_schedule_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='iskeypoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='task_type',
            field=models.CharField(choices=[('进度', '进度'), ('付款', '付款'), ('会议', '会议'), ('流程', '流程'), ('发文', '发文'), ('招采审核', '招采审核'), ('方案评审会', '方案评审会'), ('其他', '其他')], default='其他', max_length=20),
        ),
    ]
