# Generated by Django 4.0.1 on 2023-08-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_schedule_iskeypoint_schedule_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='iskeypoint',
        ),
        migrations.AddField(
            model_name='schedule',
            name='isfin',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_state',
            field=models.CharField(choices=[('前期', '前期'), ('设计', '设计'), ('招标', '招标'), ('合同流程', '合同流程'), ('实施', '实施'), ('验收完成', '验收完成'), ('完结', '完结'), ('暂停', '暂停'), ('其他', '其他')], max_length=20),
        ),
    ]
