# Generated by Django 4.0.1 on 2023-08-12 10:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_remove_schedule_iskeypoint_schedule_isfin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='iskey',
            field=models.BooleanField(default=False, verbose_name='是否关键节点'),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='project',
            name='businessentity',
            field=models.CharField(choices=[('集团', '集团'), ('管委会', '管委会')], default='集团', max_length=6, verbose_name='主体'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容简介'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_projects', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lcdate',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lcuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_projects', to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_projects', to='projects.project', verbose_name='父项目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='remark',
            field=models.CharField(blank=True, max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='project',
            name='task_state',
            field=models.CharField(choices=[('前期', '前期'), ('设计', '设计'), ('招标', '招标'), ('合同流程', '合同流程'), ('实施', '实施'), ('验收完成', '验收完成'), ('完成', '完成'), ('暂停', '暂停'), ('其他', '其他')], default='其他', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='transactor',
            field=models.CharField(max_length=32, verbose_name='经办人'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='cdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_schedules', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lcdate',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lcuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_schedules', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=128, verbose_name='事项'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='进度占比'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='projects.project', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='remark',
            field=models.CharField(blank=True, max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='task_type',
            field=models.CharField(choices=[('进度', '进度'), ('付款', '付款'), ('会议', '会议'), ('流程', '流程'), ('发文', '发文'), ('招采审核', '招采审核'), ('方案评审会', '方案评审会'), ('其他', '其他')], default='其他', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='transactor',
            field=models.CharField(max_length=32, verbose_name='经办人'),
        ),
    ]
