# Generated by Django 4.0.6 on 2023-08-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_schedule_iskey_alter_project_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='金额'),
        ),
    ]
