# Generated by Django 4.0.1 on 2022-02-08 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('businessentity', models.CharField(choices=[('集团', '集团'), ('管委会', '管委会')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lcdate', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_budgets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.department', verbose_name='部门')),
                ('lcuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('businessentity', models.CharField(choices=[('集团', '集团'), ('管委会', '管委会')], max_length=6)),
                ('paydate', models.DateTimeField(default=django.utils.timezone.now)),
                ('transactor', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('remark', models.CharField(blank=True, max_length=256)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays', to='cost.budget')),
                ('cuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_pays', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='accounts.department', verbose_name='部门')),
                ('lcuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_pays', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='cost.budgetyear'),
        ),
    ]
