# Generated by Django 4.0.1 on 2023-08-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_structure_alter_oauser_department'),
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.structure', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='accounts.structure', verbose_name='部门'),
        ),
    ]
