# Generated by Django 4.0.1 on 2023-10-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='businessentity',
            field=models.CharField(choices=[('集团', '集团'), ('管委会', '管委会')], default='集团', max_length=6),
        ),
        migrations.AlterField(
            model_name='budgetyear',
            name='year',
            field=models.DecimalField(decimal_places=0, max_digits=4, unique=True),
        ),
    ]
