# Generated by Django 4.0.1 on 2022-01-10 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='cdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='budget',
            name='lcdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='paydate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pay',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
