# Generated by Django 4.0.1 on 2022-01-11 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('cost', '0002_alter_budget_cdate_alter_budget_lcdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays', to='projects.project'),
        ),
    ]
