# Generated by Django 4.0.1 on 2022-01-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0004_budgetyear_alter_budget_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='remark',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='pay',
            name='remark',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
