# Generated by Django 4.0.1 on 2023-08-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0002_alter_budget_department_alter_pay_department'),
        ('projects', '0004_alter_project_department_alter_schedule_department'),
        ('accounts', '0002_structure_alter_oauser_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
